#!/bin/vbash

# NOTE: This is for version VyOS 1.4
# Created 2026-03-14 - Lucas

# Purpose
# -------
# Apply a restrictive outbound firewall policy to the VyOS router
# that blocks unauthorized traffic leaving the internal network.
#
# This script is intended for use in a defensive environment
# such as CCDC where compromised hosts may attempt to beacon
# to external command-and-control infrastructure.
#
# What this script does
# ---------------------
# 1. Enters VyOS configuration mode
# 2. Sets the IPv4 FORWARD chain default policy to DROP
# 3. Allows only ESTABLISHED and RELATED connections
# 4. Logs and drops all other transit traffic
# 5. Commits the configuration with a rollback timer
# 6. Saves the configuration
#
# Security effect
# ---------------
# - Blocks outbound beaconing malware from internal hosts
# - Allows return traffic for already-established connections
# - Logs denied packets for forensic analysis
#
# Important VyOS firewall chains
# -------------------------------
# input   = traffic destined for the router itself
# output  = traffic generated by the router
# forward = traffic passing THROUGH the router
#
# This script modifies the FORWARD chain because we want to
# control traffic traveling through the router from internal
# machines to external networks.
#
# Safety
# ------
# Uses `commit-confirm 5` which will automatically rollback the
# firewall changes after 5 minutes if they are not confirmed.
# This prevents accidentally locking yourself out of the router.
#
# Usage
# -----
# ./5rule-setup.sh
#
# Author
# ------
# CyberHawks CCDC defensive automation
# ============================================================

if [ "$(id -g -n)" != "vyattacfg" ]; then
    exec sg vyattacfg -c "/bin/vbash $(readlink -f "$0") $@"
fi

source /opt/vyatta/etc/functions/script-template
set -e

echo "[*] Applying transit outbound block"

configure

set firewall ipv4 forward filter default-action 'drop'

# Web server
set firewall ipv4 forward filter rule 50 action 'accept'
set firewall ipv4 forward filter rule 50 protocol 'tcp'
set firewall ipv4 forward filter rule 50 destination port '80,443'
set firewall ipv4 forward filter rule 50 description 'Allow scored web traffic'

# Webmail / mail
set firewall ipv4 forward filter rule 60 action 'accept'
set firewall ipv4 forward filter rule 60 protocol 'tcp'
set firewall ipv4 forward filter rule 60 destination port '25,465,587,110,995,143,993,80,443'
set firewall ipv4 forward filter rule 60 description 'Allow scored mail/webmail traffic'

# AD / DNS
set firewall ipv4 forward filter rule 70 action 'accept'
set firewall ipv4 forward filter rule 70 protocol 'tcp_udp'
set firewall ipv4 forward filter rule 70 destination port '53,88,389,445,135,464,123'
set firewall ipv4 forward filter rule 70 description 'Allow scored AD/DNS traffic'

# FTP
set firewall ipv4 forward filter rule 80 action 'accept'
set firewall ipv4 forward filter rule 80 protocol 'tcp'
set firewall ipv4 forward filter rule 80 destination port '21'
set firewall ipv4 forward filter rule 80 description 'Allow scored FTP control traffic'

# Established / related
set firewall ipv4 forward filter rule 900 action 'accept'
set firewall ipv4 forward filter rule 900 state established
set firewall ipv4 forward filter rule 900 state related
set firewall ipv4 forward filter rule 900 description 'Allow established and related traffic'

# Final drop
set firewall ipv4 forward filter rule 999 action 'drop'
set firewall ipv4 forward filter rule 999 log
set firewall ipv4 forward filter rule 999 description 'Drop and log all other transit traffic'

echo "[*] Pending firewall configuration:"
show | compare
echo

echo "[*] Firewall rules that will be applied:"
run show configuration commands | match firewall
echo

echo "[*] Applying firewall rules with 5-minute rollback safety"
commit-confirm 5
save

echo
echo "[*] Firewall rules applied TEMPORARILY"
echo "[*] Verify them with:"
echo "    show configuration commands | match firewall"
echo "    sudo nft list ruleset"
echo
echo "[*] If everything looks good, run:"
echo "    confirm"
echo
echo "[*] If something broke, do nothing and the config will rollback in 5 minutes"
echo

exit